Added a sweet alert notifier pop up
Luyimbazi-Timothy/Internship-2024 pull request #12
Opened 2024-07-30 14:37 UTC by DerrickLegacy

2024-07-30 14:51 UTC, Nakatolynn commented on src/pages/AppraisalActivity/ActivityTableData/AddNewInitiativeDetailsModal.jsx
> +function AddNewInitiativeDetailsModal({displyaSuccessMessage, measurableActivity, show, handleClose }) {
Change this to displaySuccessMessage

2024-07-30 14:53 UTC, Nakatolynn commented on src/pages/AppraisalActivity/ActivityTableData/DetailPage.js
> +    console.log('saved');
Remove this  Console.log please

2024-07-30 14:54 UTC, Nakatolynn commented on src/pages/AppraisalActivity/ActivityTableData/DetailPage.js
>                console.log("Delete action for row:", row.original);
Derrick this console should be removed.

2024-07-30 14:56 UTC, Nakatolynn commented on src/pages/Dashboard/Dashboard.js
> +        position: 'top',
position:'center'

2024-07-31 07:10 UTC, mariotury requested changes
make changes to everything as stated in the comments. Also note that the appraisal details page is not as we agreed. Make the Measurable Activitiy stand out.
![Screenshot 2024-07-31 100750](https://github.com/user-attachments/assets/8ba6e945-f931-4618-b420-4fe23a120c39)

2024-07-31 07:10 UTC, mariotury commented on src/pages/Dashboard/Dashboard.js
> +        position: 'top',
@DerrickLegacy the welcome alert is showing every time the page reloads. correct that please.

2024-07-31 07:10 UTC, mariotury commented on src/pages/AppraisalActivity/ActivityTableData/DetailPage.js
> +    console.log('saved');
@DerrickLegacy what you have done for the delete function with the sweetrAlerts, do the same for the edit function.

![Uploading Screenshot 2024-07-31 100518.png…]()

2024-07-31 07:15 UTC, closed without merging

2024-07-31 07:17 UTC, mariotury commented on src/pages/Dashboard/Dashboard.js
> +        position: 'top',
What value is it adding, again?